language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:~/nginx/sbin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=ecl

install:
  # Roswell
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/master/scripts/install-for-ci.sh | sh
  # prove
  - ros install prove

cache:
  directories:
    - $HOME/.roswell
    - $HOME/nginx
    - $HOME/.config/common-lisp

before_script:
  - ros --version
  - ros config

script:
  - ros -e '(ql:quickload (list :fiveam :cl-coveralls))'
        -e '(setf fiveam:*debug-on-error* t
                  fiveam:*debug-on-failure* t)'
        -e '(setf *debugger-hook*
                  (lambda (c h)
                    (declare (ignore c h))
                    (uiop:quit -1)))'
        -e '(ql:quickload :ansi-spec-test)'
        -e '(ansi-spec-test:run-tests)'

notifications:
  email:
    - eudoxiahp@gmail.com
